---
  # Output paths.
  use_scene_path: "./use_scene.json"

  flow_path_fastflowkitti: ["./fastflow_kitti/flow_train",
                            "./fastflow_kitti/flow_valid"]
  raw_flow_path_fastflowkitti: ["./fastflow_kitti/raw_with_flow_train",
                                "./fastflow_kitti/raw_with_flow_valid"]

  flow_path_raftkitti: ["./raft_kitti/flow_train",
                        "./raft_kitti/flow_valid"]
  raw_flow_path_raftkitti: ["./raft_kitti/raw_with_flow_train",
                            "./raft_kitti/raw_with_flow_valid"]

  label_path_fastflowkitti: ["./fastflow_kitti/labels_train.csv",
                               "./fastflow_kitti/labels_valid.csv"]

  labels_path_raftkitti: ["./raft_kitti/labels_train.csv",
                          "./raft_kitti/labels_valid.csv"]

  rawlst_path: ["./rawlst_train.json",
                "./rawlst_valid.json"]

  writer_path: "./dev/runs"
  model_path: "./dev/models"
  checkpoint_path: "./dev/model_checkpoint"
  visual_path: "./visual_img"

  # Other paths.
  nuscenes_path: "{}"   # Please fill in the path of nuScenes dataset

  # For demo.
  demo_label_path: "./demo/demo_label.csv"
  demo_raw_path: "./demo/demo_raw"
  demo_visual_path: "./demo/demo_infer"


  # scene_filter.py
  exclusion: ["night", "rain", "lightning"]

  # select_trainset.py
  # generate_label.py
  sensor: "CAM_FRONT"
  use_category: ["vehicle.car", "vehicle.emergency.ambulance", "vehicle.emergency.police",
                 "vehicle.truck", "vehicle.bus.bendy", "vehicle.bus.rigid", "vehicle.construction"]
  use_visibility: "v80-100"
  scene_num_train: 550
  min_dist: 30
  max_dist: 70
  threshold_vel: 2.0

  # dataset.py
  re_size: 224
  sampling_frac_train: [3, 5]
  sampling_frac_valid: [1, 2]

  # model_train.py
  num_epoch: 60
  batch_size: 128
  learning_rate: 0.002
  batches_per_iter: 60
  num_workers: 8
  momentum: 0.0
  weight_decay: 0.0